### ISSUE TITLE
US7 - Select Table

### ISSUE THREAD

**Issue by henkegithub** [henkegithub/instroke-app#6]
### Value proposition

As a user
I want to select a table
in order to add a table number to the order and submit the order by clicking checkout and see the successful order with a  table number displayed on a different page

## Description

![Image](https://github.com/henkegithub/instroke-app/assets/135317916/69beb477-34be-4622-aa51-08351912977b)

## Acceptance criteria

- [ ] a table number can be selected in a dropdown menu
- [ ] the order can be submitted with the correct table number selected
- [ ] the table number will be displayed on the order finish page

## Tasks

- [ ] create feature branch feature/select-table
- [ ] create a dropdown menu
- [ ] create an input type=number and limit the range of the input from 1 to 100
- [ ] create a new page called "order-finish"
- [ ] create a checkout link to "order-finish" page
- [ ] display the table number and some dummy data on the page

## Size: M

**Comment by Roland-Hufnagel** [comment]
Hi Michael. Some things you have to keep in mind:
- Please give your userstories a good title. Not in the userstory itself but in the issue there is a title-input-field you should use. As you can see in your project, all your stories are only displayed with: 'US1', 'US2', ... 
- In all your userstories your first task is 'create feature-branch feature/title-name'. Of cause each US has a different feature-brach. Please change this.
- Where is the header-component from US3?

**Comment by ninaassmann** [comment]
is the list 1 - 100 a dropdown? 

"Create a input field" - for what? does the user type the table number here?

**Comment by F-Kirchhoff** [comment]
I would suggest do use an input type=number here and limit the range of the input from 1 to 100. 
Please also sketch the input accordingly, in your current wireframe its not clear what element is supposed to be the dropdown / number input.

**Comment by mbosselmann** [comment]
Hi Michael,
as I am the next person to review your US I am happy that you though about the remarks of my former reviewers. Nevertheless I also have some remarks for you:

- "the order can be submitted with the correct table number selected" I asked myself if there is the possibility that the user can select the wrong table number and if so what happens. If the user does always select the correct number maybe the `correct` is not needed?
- And what does happen after clicking the checkout button? For me it is not clear if the table is added to the table list or anything else happens? I think this should be visible as wireframe and / or described in your acceptance criteria.

I hope this does help in improving your user story! 💪

**Comment by FabianRuettgers** [comment]
LGTM
