### ISSUE TITLE
US5 - Adding Link to the order menu to get back to the opening page

### ISSUE THREAD

**Issue by henkegithub** [henkegithub/instroke-app#7]
## Value proposition

As a User
I want to get back to the opening page
in order to see the restaurant overview

## Description

![Image](https://github.com/henkegithub/instroke-app/assets/135317916/e5a2819c-4484-4078-b33f-50aa63810677)

## Acceptance criteria

- [ ] Link with text "Go Back" on Order List Page
- [ ] Link direkts to Opening Page

## Tasks

- [ ] create feature branch feature/(insert-title-here)
- [ ] create link on order-list page that leads to opening-page
- [ ] give link a text "Back"

Size: XS

**Comment by Roland-Hufnagel** [comment]
Hi Michael. Like I mentioned in previous US:
- Please give your userstories a good title. Not in the userstory itself but in the issue there is a title-input-field you should use. As you can see in your project, all your stories are only displayed with: 'US1', 'US2', ... 
- the name of the feature-branch should fit the feature of your US. 'feature/project-title' does not correspond to this US.

**Comment by henkegithub** [comment]
> Hi Michael. Like I mentioned in previous US:
> 
> * Please give your userstories a good title. Not in the userstory itself but in the issue there is a title-input-field you should use. As you can see in your project, all your stories are only displayed with: 'US1', 'US2', ...
> * the name of the feature-branch should fit the feature of your US. 'feature/project-title' does not correspond to this US.

I changed the titles. the feature-branch will be named like the title is displayed ( to not always have to write the same thing twice) it is a kinda insert here space. hope that is not that big of an issue!

**Comment by Frank-Schaeske** [comment]
LGTM, but you should be consistent with the link text.
