### ISSUE TITLE
US4 - counting on order menu

### ISSUE THREAD

**Issue by henkegithub** [henkegithub/instroke-app#8]
## Value proposition

As a user
I want to be able to count specific food
in order to display the amount of food selected

## Description

![Image](https://github.com/henkegithub/instroke-app/assets/135317916/13543a22-696a-436b-b79e-a6c677ea5200)

## Acceptance criteria

- [ ] A + and a - button are displayed next to each food item
- [ ] Items can be added or removed from the order list
- [ ] Below you can see the sum of what has been counted

## Tasks

- [ ] create a feature branch feature/title-name
- [ ] create add(+) and remove(-) buttons to each menu item
- [ ] create a count function
- [ ] display a item summary that has been added or removed to a list at the bottom

Size: XL

**Comment by Roland-Hufnagel** [comment]
Isn't this exactly the same as US4?

**Comment by Frank-Schaeske** [comment]
Hi Michael, from your description I don't really understand how the user can add or remove items. You mention buttons later in your tasks but I think you should include them in the image and maybe also in the acceptance criteria. Moreover, I think you forgot to adapt the name of your feature branch.

**Comment by henkegithub** [comment]
> Hi Michael, from your description I don't really understand how the user can add or remove items. You mention buttons later in your tasks but I think you should include them in the image and maybe also in the acceptance criteria. Moreover, I think you forgot to adapt the name of your feature branch.

I use the featurebanch title-name as an insert space where the title of the user story gets replaced with

I will include them in the image and explain further how the user can add or remove items.

**Comment by CJAkkuec** [comment]
Hey there!

Some notes:

> As a user
> I want to be able to count specific food
> in order to display the amount of food selected

_Specific_ food, or any food? The wording aside, I think what you're trying to say is that the user wants to add food to their order and then increase and decrease the total amount of the food they added to the order. I've checked, and I don't really see any user story that talks about adding food items to an order, just the US3 that features an order menu.

I think you need to clarify the process of ordering a little more.

1. Make sure that the feature titles match their description. This is mostly a wording issue. The "order menu" of US3 is actually just ... a menu. The menu of food items available to be ordered.
2. This user story is about the order itself, which I understand, but it's not ultimately clear. It's fair enough to want to include a counter next to each item, but where does that information end up? I think this user story should include a component that acts as a "shopping cart" that displays the food items added to the order. Otherwise we have a counter that essentially doesn't do anything. You also don't want to have to scroll up and down and sideways through the restaurant menu if you want to increase/decrease your number of food items to order, you should also be able to do it in one spot - again, something like a "shopping cart".
3. If you're aware of all this, and the items below the line in your wireframe is the "shopping cart", then you need to be a lot more clear in your descriptions and visuals. It's a bit difficult to follow, and ultimately these user stories aren't something you're writing for yourself in the "real world" - it's for the other people in your team. For example, where are the +/- buttons in your wireframe?

Re: Acceptance Criteria
> + and - Button will be added on each item

By the user? I think it should rather say "A + and a - button are displayed next to each food item".

> Items can be added to the order by clicking/pressing the + button
> Items can be removed from the order by clicking/pressing the - button

> Below you can see the sum of what has been counted

Below what? Imagine the total number of food items on the restaurant menu is 100+. If the user has to scroll past all that to get to the summary/cart/etc. it's be a not-so-user-friendly experience. Perhaps the summary is best displayed on top of the page for the time being. Later the cart can be an item of your navigation and be displayed as a modal.

Re: Tasks
> create a feature branch feature/title-name
Please no placeholder names for the feature branches.

And here's some suggestions ...
> create two button components that let the user add and remove food items to their order
> implement the logic required to allow the user to add food items to their order
> implement the logic required to allow the user to increase and decrease the number of food items added to their order
> create an `OrderCart` component that displays a food item summary of the items currently added to the user's order

Ultimately, the name of the component doesn't have to be `OrderCart`, it can also be `Order`, etc. Depending on your established naming convention.

We're not trying to annoy you with the feedback we're giving you. :) The user stories are your chance to explain to others (and most importantly yourself) what you need to do.

**Comment by ninaassmann** [comment]
LGTM
